const PDFDocument = require("pdfkit");

const generateInvoicePDF = async (req, res) => {
  try {
    const {
      companyName,
      buyerName,
      product,
      quantity,
      price,
      country,
      notes,
    } = req.body;

    const doc = new PDFDocument({ margin: 50 });

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      "attachment; filename=tradeflow-invoice.pdf"
    );

    doc.pipe(res);

    doc
      .fontSize(24)
      .fillColor("#0ea5e9")
      .text("TradeFlow Export Invoice", { align: "center" });

    doc.moveDown();

    doc
      .fontSize(12)
      .fillColor("#000")
      .text(`Exporter Company: ${companyName || "N/A"}`)
      .text(`Buyer Name: ${buyerName || "N/A"}`)
      .text(`Destination Country: ${country || "N/A"}`);

    doc.moveDown();

    doc
      .fontSize(16)
      .text("Product Details", { underline: true });

    doc.moveDown();

    doc
      .fontSize(12)
      .text(`Product: ${product || "N/A"}`)
      .text(`Quantity: ${quantity || "N/A"}`)
      .text(`Unit Price: ${price || "N/A"}`);

    const total =
      Number(quantity || 0) * Number(price || 0);

    doc.text(`Total Value: ${total}`);

    doc.moveDown();

    doc
      .fontSize(16)
      .text("Notes", { underline: true });

    doc.moveDown();

    doc
      .fontSize(12)
      .text(notes || "Generated by TradeFlow Cloud.");

    doc.moveDown(2);

    doc
      .fontSize(10)
      .fillColor("#555")
      .text("Generated by TradeFlow Cloud SaaS OS", {
        align: "center",
      });

    doc.end();
  } catch (error) {
    res.status(500).json({
      message: error.message,
    });
  }
};

module.exports = {
  generateInvoicePDF,
};