Foreground yes
TCPSocket 3310
TCPAddr 0.0.0.0
User clamav
LogTime yes
LogClean no
ExtendedDetectionInfo no
StreamMaxLength 9M
MaxFileSize 9M
MaxScanSize 16M
MaxRecursion 8
MaxFiles 256
MaxEmbeddedPE 9M
ScanArchive yes
AlertEncryptedArchive yes
