const express = require("express");
const axios = require("axios");

const Supplier = require("../models/Supplier");
const Deal = require("../models/Deal");
const Outreach = require("../models/Outreach");
const Notification = require("../models/Notification");
const { writeAuditLog } = require("../utils/auditLogger");

const router = express.Router();

function getOwnerEmail(req) {
  return (
    req.tenant?.ownerEmail ||
    req.user?.email ||
    req.headers["x-user-email"] ||
    req.body?.email ||
    req.query?.email ||
    "unknown@tradeflow.local"
  )
    .toLowerCase()
    .trim();
}

function getHunterKey() {
  return process.env.HUNTER_API_KEY || "";
}

function extractDomain(website = "") {
  try {
    let clean = website.trim();

    if (!clean.startsWith("http")) {
      clean = "https://" + clean;
    }

    return new URL(clean).hostname.replace("www.", "");
  } catch {
    return "";
  }
}

async function hunterDomainSearch(domain) {
  if (!domain || !getHunterKey()) return null;

  const response = await axios.get("https://api.hunter.io/v2/domain-search", {
    params: {
      domain,
      api_key: getHunterKey()
    }
  });

  return response.data;
}

function pickBestEmail(hunterData) {
  const emails = hunterData?.data?.emails || [];

  if (!emails.length) return "";

  const best = emails.sort((a, b) => {
    return Number(b.confidence || b.score || 0) - Number(a.confidence || a.score || 0);
  })[0];

  return best?.value || best?.email || "";
}

function leadScore({ supplier, email }) {
  let score = 50;

  if (email) score += 25;
  if (supplier.website) score += 10;
  if (supplier.phone) score += 5;
  if (supplier.country) score += 5;
  if (supplier.product) score += 5;

  return Math.max(0, Math.min(100, score));
}

router.post("/enrich-supplier/:id", async (req, res) => {
  try {
    const ownerEmail = getOwnerEmail(req);

    const supplier = await Supplier.findOne({
      _id: req.params.id,
      ownerEmail
    });

    if (!supplier) {
      return res.status(404).json({
        success: false,
        message: "Supplier not found"
      });
    }

    const domain = extractDomain(supplier.website || supplier.url || "");

    if (!domain) {
      return res.status(400).json({
        success: false,
        message: "Supplier website/domain missing"
      });
    }

    const hunterData = await hunterDomainSearch(domain);
    const bestEmail = pickBestEmail(hunterData);

    const score = leadScore({
      supplier,
      email: bestEmail
    });

    supplier.email = bestEmail || supplier.email || "";
    supplier.aiLeadScore = score;
    supplier.enrichmentStatus = bestEmail ? "Enriched" : "No Email Found";
    supplier.hunterDomain = domain;

    await supplier.save();

    const outreachMessage = `Hello,

We are interested in exploring export/import collaboration opportunities with your company.

Please share your product catalog, MOQ, pricing, certifications, and shipment timeline.

Regards,
TradeFlow Team`;

    let outreach = null;

    if (bestEmail) {
      outreach = await Outreach.create({
        ownerEmail,
        companyId: supplier.companyId || null,
        workspaceId: supplier.workspaceId || null,
        contactName: supplier.supplierName || supplier.name || "Supplier",
        outreachContactName: supplier.supplierName || supplier.name || "Supplier",
        email: bestEmail,
        product: supplier.product || "",
        outreachProduct: supplier.product || "",
        message: outreachMessage,
        outreachMessage,
        status: "Draft",
        notes: "Generated by AI Lead Enrichment Pipeline using Hunter."
      });
    }

    const deal = await Deal.create({
      ownerEmail,
      companyId: supplier.companyId || null,
      workspaceId: supplier.workspaceId || null,
      companyName: supplier.supplierName || supplier.name || "Supplier Lead",
      dealCompanyName: supplier.supplierName || supplier.name || "Supplier Lead",
      product: supplier.product || "",
      dealProduct: supplier.product || "",
      email: bestEmail || "",
      value: 0,
      dealValue: 0,
      stage: bestEmail ? "Contacted" : "New Lead",
      aiScore: score,
      aiPrediction: score >= 75 ? "High Probability" : "Needs Verification"
    });

    await Notification.create({
      ownerEmail,
      companyId: supplier.companyId || null,
      workspaceId: supplier.workspaceId || null,
      title: "AI Lead Enrichment Completed",
      message: bestEmail
        ? `Hunter found ${bestEmail} for ${supplier.supplierName || supplier.name || "supplier"}.`
        : `No verified email found for ${supplier.supplierName || supplier.name || "supplier"}.`,
      type: "AI",
      severity: bestEmail ? "Medium" : "High",
      read: false,
      isRead: false
    });

    await writeAuditLog(req, {
      module: "AI",
      action: "Ran AI lead enrichment",
      entityType: "Supplier",
      entityId: String(supplier._id),
      severity: "Medium",
      metadata: {
        domain,
        bestEmail,
        score,
        outreachCreated: !!outreach,
        dealCreated: !!deal
      }
    });

    res.json({
      success: true,
      message: "AI lead enrichment completed",
      supplier,
      bestEmail,
      score,
      outreach,
      deal
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: "AI lead enrichment failed",
      error: error.response?.data || error.message
    });
  }
});

module.exports = router;